export default {
	about: "about",
	author: "author",
	interval: "interval",
	circle: "circle",
	mobile_ksQuery: "m.key",
	tablet_scaleQuery: "scale",
	mobile_scaleTable: "m.scale",
	mobile_scoreChecker: "m.q.score",
	settings: "settings",
	spiano: "s.piano",
	temp251: "temp251",
	chordDisplay: "chord",
	findNotes: "n.find",
	findNotesWithInterval: "n.i.find",
	harmonicSeries: "h.series",
	staveExam: "exam",
	upgradeLog: "log",
	keyboard: "keyboard",
}
